# @package _global_
dropout: 0.0
batch_norm: False

# Feature extractor dim
input_dim: 3

out_channels: [8, 16, 32, 64]
kernel_dims: [3, 3, 3, 3]
stride: [1, 1, 1, 1]
padding: [1, 1, 1, 1]

# classifier dim
in_feat: 64
out_feat: [32, 8, 1]
