# @package _global_

eval:
  batch_size: 4
  num_workers: 0  # 12
  pin_memory: True
  drop_last: False
  shuffle: True

  device: 'cpu'  # 'cuda:0', 'cpu'
  use_lightning_loader: False
  use_ensemble: False

  data_augmentation: True
  resize_transform_only: True  # set true to plot both supervised and unsupervised boxes

  # dataset
  root: '/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/Datasets/SDD/'
  video_class: GATES
  video_meta_class: GATES
  desired_pixel_to_meter_ratio: 0.07
  desired_pixel_to_meter_ratio_rgb: 0.07 # 0.07 # 0.25 # 0.05
  downscale_only_target_maps: False
  using_replay_compose: True
  manual_annotation_processing: False
  frame_rate: 30.  # 30.

  video_based:
    enabled: True  # True
    frames_per_clip: 4  # for video based
    gt_idx: -1

  test:
    num_videos: -1
    video_number_to_use: 3
    #    video_classes_to_use: [ BOOKSTORE, COUPA, DEATH_CIRCLE, GATES, HYANG, LITTLE, NEXUS, QUAD ]
    #    video_numbers_to_use: [ [ 6 ], [ 3 ], [ 3 ], [ 7 ], [ 9, 14 ], [ 0 ], [ 6 ], [ 0 ] ]
    video_classes_to_use: [ DEATH_CIRCLE ]  # [ GATES, DEATH_CIRCLE, LITTLE ]
    video_numbers_to_use: [ [ 4 ] ]  # [ [ 4 ], [ 3 ], [ 0 ] ]
    multiple_videos: False

    single_video_mode:
      enabled: False

      num_videos: -1
      video_classes_to_use: [ LITTLE ]
      video_numbers_to_use: [ [ 0 ] ] # nexus 3, 4 are bad
      multiple_videos: False

      val_percent: 0.2

  dataset_workers: 12
  # keep one of them null at one time
  scale_factor: null # 0.25
  desired_size: [ 490, 360 ]

  use_generated_dataset: True

  plot_samples: False

  loss:
    reduction: 'mean'
    gaussian_weight: [ 0.5 ]
    apply_sigmoid: [ True ]
    bfl:
      alpha: 0.85
      gamma: 4.0

  model: 'DeepLabV3PlusTemporal2D'  # DeepLabV3PlusTemporal2D, DeepLabV3Plus

  preproccesing:
    pad_factor: 8

  # gaussian
  heatmap_shape: null
  return_combined_heatmaps: True
  sigma: 1.0

  seg_map_objectness_threshold: 0.5
  heatmap_region_limit_threshold: 0.0
  focal_loss_alpha: 0.8
  gaussuan_focal_loss_alpha: 2.0
  pick_heatmap_from_stack_number: -2

  # one of 'PositionMapUNetHeatmapRegression', 'PositionMapUNetPositionMapSegmentation',
  # 'PositionMapUNetClassMapSegmentation', 'PositionMapUNetHeatmapSegmentation', 'PositionMapStackedHourGlass',
  # 'HourGlassPositionMapNetwork'
  postion_map_network_type: 'HourGlassPositionMapNetwork'

  show_plots: True
  plot_checkpoint: 1
  plot_save_dir: '/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/Plots/proposed_method/v0/position_maps/'
  plot_with_overlay: True
  plots_do_nothing: False

  evaluate_precision_recall: False
  blob_threshold: 0.2
  objectness_threshold: 0.2
  gt_pred_loc_distance_threshold: 2 # meters

  objectness:
    kernel: 3
    loc_cutoff: 0.05
    marker_size: 3
    index_select: -1
    prune_radius: 10

  make_video: False
  video_fps: 2

  max_pool:
    kernel_size: 2
    stride: 1
    padding: 1

  blob_counter:
    kernel: [ 1, 1 ]
    plot: False

  checkpoint:
    root: "/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/src/position_maps/logs/"
    path: "lightning_logs/version_"
    version: 513923  # 509506 # 497829 # 492265 #424798 # 437363  # 424798 # 509506 (best-dlv3-r50) # 513512 (T2D-best-dlv3) # 511123 (LITTLE - good) # 511116 (DC-3-good)
    top_k: 1