# @package _global_

device: 'cuda:0'
data_augmentation: True

# optimizer
# Adam
lr: 5e-3
weight_decay: 0
amsgrad: False

# scheduler
# ReduceLROnPlateau
patience: 5
verbose: True
factor: 0.1
min_lr: 1e-10
# extra
monitor: 'val_loss_epoch'
interval: 'epoch'
frequency: 1

# loaders
batch_size: 4
shuffle: False  # keep it always False
num_workers: 0
pin_memory: True
drop_last: False
val_batch_size_factor: 2

# trainer
trainer:
  max_epochs : 400
  gpus : 1
  fast_dev_run: False


# dataset
root: '/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/Datasets/SDD/'
video_class: DEATH_CIRCLE
video_meta_class: DEATH_CIRCLE
desired_pixel_to_meter_ratio: 0.25
downscale_only_target_maps: True

train:
  num_videos: -1
  video_number_to_use: 2
  video_classes_to_use: [DEATH_CIRCLE, LITTLE]
  video_numbers_to_use: [[2, 4], [0, 3]]
  multiple_videos: False

val:
  num_videos: -1
  video_number_to_use: 2
  video_classes_to_use: [ DEATH_CIRCLE, LITTLE ]
  video_numbers_to_use: [ [ 2, 4 ], [ 0, 3 ] ]
  multiple_videos: False

dataset_workers: 8
# keep one of them null at one time
scale_factor: null # 0.25
desired_size: [490, 360]

use_generated_dataset: True

plot_samples: False

# gaussian
heatmap_shape: null
return_combined_heatmaps: True
sigma: 1.5

seg_map_objectness_threshold: 0.5
heatmap_region_limit_threshold: 0.5
focal_loss_alpha: 0.8

warm_restart:
  enable: False
  custom_load: False
  checkpoint:
    root: "/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/src/position_maps/logs/"
    path: "lightning_logs/version_"
    version: 0

resume_mode: False
resume:
  checkpoint:
    path: "lightning_logs/version_"
    version: 10

class_map_segmentation: False
position_map_segmentation: False

# one of 'PositionMapUNetHeatmapRegression', 'PositionMapUNetPositionMapSegmentation',
# 'PositionMapUNetClassMapSegmentation', 'PositionMapUNetHeatmapSegmentation', 'PositionMapStackedHourGlass'
postion_map_network_type: 'PositionMapUNetHeatmapSegmentation'

overfit:
  num_epochs: 6000
  batch_size: 1
  num_workers: 0
  pin_memory: True
  drop_last: False

  postion_map_network_type: 'PositionMapUNetHeatmapSegmentation'
  focal_loss_alpha: 0.9

  subset_indices: [0, 85, 32, 5, 125, 200]
#  subset_indices: [0]

  plot_checkpoint: 99




