# @package _global_

device: 'cuda:0'  # 'cuda:0'
data_augmentation: True

# optimizer
# Adam
lr: 2e-3
weight_decay: 0
amsgrad: False

# scheduler
# ReduceLROnPlateau
patience: 5
verbose: True
factor: 0.1
min_lr: 1e-10
# extra
monitor: 'val_loss_epoch'
interval: 'epoch'
frequency: 1
mode: 'min'

# TP module
# scheduler
tp_module:
  scheduler:
    patience: 5
    verbose: True
    factor: 0.1
    min_lr: 1e-10
    # extra
    monitor: 'val_loss_epoch'
    interval: 'epoch'
    frequency: 1
    mode: 'min'

  # Adam
  optimizer:
    lr: 2e-3
    weight_decay: 0
    amsgrad: False

# loaders
batch_size: 2
shuffle: False  # keep it always False
num_workers: 12
pin_memory: True
drop_last: True
val_batch_size_factor: 2

single_video_mode:
  enabled: False

  num_videos: -1
  video_classes_to_use: [ DEATH_CIRCLE ]
  video_numbers_to_use: [ [ 4 ] ] # nexus 3, 4 are bad
  multiple_videos: False

  val_percent: 0.2

# trainer
trainer:
  max_epochs: 400
  gpus: 1
  fast_dev_run: False
  num_checkpoints_to_save: 4
  deterministic: False
  accelerator: 'ddp' #'ddp_cpu' # null  # 'ddp', 'ddp_cpu'
  replace_sampler_ddp: False
  num_nodes: 1
  find_unused_parameters: True
  gradient_clip_val: 2.0


# dataset
root: '/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/Datasets/SDD/'
video_class: DEATH_CIRCLE
video_meta_class: DEATH_CIRCLE
desired_pixel_to_meter_ratio: 0.18 # 0.35
desired_pixel_to_meter_ratio_rgb: 0.18 # 0.25 # 0.05
downscale_only_target_maps: False
using_replay_compose: True
manual_annotation_processing: False
frame_rate: 15.  # 30.

video_based: # !!!!! Keep an eye !!!!
  enabled: False
  frames_per_clip: 8  # for video based
  gt_idx: -1

train:
  num_videos: -1
  video_number_to_use: 4
  # all videos
  #  video_classes_to_use: [ BOOKSTORE, COUPA, DEATH_CIRCLE, GATES, HYANG, LITTLE, NEXUS, QUAD ]
  #  video_numbers_to_use: [ [ 1, 2, 3, 4, 5 ], [ 0, 1, 2 ], [ 0, 1, 2, 4 ], [ 0, 1, 2, 3, 5, 6, 8 ],
  #                          [ 0, 1, 2, 3, 4, 5, 6, 8, 10, 11, 12, 13 ], [ 1, 2, 3 ],
  #                          [ 0, 1, 2, 7, 8, 9, 10, 11 ], [ 1, 2, 3 ] ] # nexus 3, 4 are bad
  #  # Portraits -> H > W
  #  video_classes_to_use: [ DEATH_CIRCLE, GATES, HYANG, LITTLE, NEXUS ]
  #  video_numbers_to_use: [ [ 0, 1, 2, 4 ], [ 0, 1, 2, 3, 5, 6, 8 ],
  #                          [ 0, 1, 4, 5, 8 ], [ 1, 2, 3 ],
  #                          [ 0, 1, 2, 7, 8, 9, 10, 11 ] ] # nexus 3, 4 are bad
  # Portraits -> H > W
  video_classes_to_use: [ DEATH_CIRCLE ]
  video_numbers_to_use: [ [ 3 ]] # nexus 3, 4 are bad
  multiple_videos: False

val:
  num_videos: -1
  video_number_to_use: 2
  # all videos
  #  video_classes_to_use: [ BOOKSTORE, COUPA, DEATH_CIRCLE, GATES, HYANG, LITTLE, NEXUS, QUAD ]
  #  video_numbers_to_use: [ [ 0 ], [ 3 ], [ 3 ], [ 4 ], [ 7 ], [ 0 ], [ 6 ], [ 0 ] ]
  # Portraits -> H > W
  # Portraits -> H > W
  #  video_classes_to_use: [ DEATH_CIRCLE, GATES, HYANG, LITTLE, NEXUS ]
  #  video_numbers_to_use: [ [ 3 ], [ 4 ], [ 7 ], [ 0 ], [ 6 ] ]
  video_classes_to_use: [ DEATH_CIRCLE ]
  video_numbers_to_use: [ [ 2 ] ]
  multiple_videos: False

dataset_workers: 12
# keep one of them null at one time
scale_factor: null # 0.25
desired_size: [ 490, 360 ]

use_generated_dataset: True

plot_samples: False

# gaussian
heatmap_shape: null
return_combined_heatmaps: True
sigma: 2.5 # 3.2 # 0.7

seg_map_objectness_threshold: 0.5
heatmap_region_limit_threshold: 0.0
focal_loss_alpha: 0.8
gaussuan_focal_loss_alpha: 2.0
use_center_net_gaussian_focal_loss: True

model: 'DeepLabV3PlusDDP'

preproccesing:
  pad_factor: 8

loss:
  reduction: 'mean'
  gaussian_weight: [ 0.5 ]
  apply_sigmoid: [ True ]
  bfl:
    alpha: 0.85
    gamma: 4.0

prediction:
  threshold: 0.4
  fill_value: 0.0

warm_restart:
  enable: False
  custom_load: False
  checkpoint:
    root: "/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/src/position_maps/logs/"
    path: "lightning_logs/version_"
    version: 492265
    top_k: 1

resume_mode: False
resume:
  checkpoint:
    path: "lightning_logs/version_"
    version: 472698
    top_k: 1

class_map_segmentation: False
position_map_segmentation: False

# one of 'PositionMapUNetHeatmapRegression', 'PositionMapUNetPositionMapSegmentation',
# 'PositionMapUNetClassMapSegmentation', 'PositionMapUNetHeatmapSegmentation', 'PositionMapStackedHourGlass',
# 'HourGlassPositionMapNetwork', 'HourGlassPositionMapNetworkDDP'
postion_map_network_type: 'HourGlassPositionMapNetworkDDP'

from_model_hub: True
model_hub:
  model: 'DeepLabV3Plus'

overfit:
  num_epochs: 6000
  batch_size: 2
  num_workers: 0
  pin_memory: True
  drop_last: False

  postion_map_network_type: 'HourGlassPositionMapNetwork'
  focal_loss_alpha: 0.9
  gaussuan_focal_loss_alpha: 2.0

  subset_indices: 128  # 450  # [ 0, 85, 32, 5, 125, 200 ]
  #  subset_indices: [0]

  plot_checkpoint: 99

  temporal_stacked:
    enabled: True
    frames_per_clip: 5

  use_pretrained:
    enabled: False
    checkpoint:
      root: "/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/src/position_maps/logs/"
      path: "lightning_logs/version_"
      version: 509506 # 492265 # 497829 # 492265 #424798 # 437363  # 424798
      top_k: 1

interplay_v0:
  num_epochs: 400

  use_pretrained:
    enabled: True
    checkpoint:
      root: "/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/src/position_maps/logs/"
      path: "lightning_logs/version_"
      version: 509506 # 492265 # 497829 # 492265 #424798 # 437363  # 424798
      top_k: 1

  train_position_model: True

  subset_indices: 128  # 450  # [ 0, 85, 32, 5, 125, 200 ]

  batch_size: 2
  shuffle: False  # keep it always False
  num_workers: 12
  pin_memory: True
  drop_last: True

  min_history: 4
  inactive_tracks_keep_alive: 5


interact:
  device: 'cuda:0'

  lr: 2e-3
  weight_decay: 0
  amsgrad: False

  num_epochs: 6000
  batch_size: 4
  num_workers: 0
  pin_memory: True
  drop_last: False

  num_videos: -1
  video_classes_to_use: [ DEATH_CIRCLE ]
  video_numbers_to_use: [ [ 2 ] ]
  multiple_videos: False

  desired_pixel_to_meter_ratio: 0.25
  desired_pixel_to_meter_ratio_rgb: 0.25 # 0.05

  postion_map_network_type: 'PositionMapUNetHeatmapSegmentation'
  focal_loss_alpha: 0.9

  max_trajectory_length: 18

  subset_indices: [ 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85 ]  # [0, 12, 24, 36, 48, 60]

  plot_checkpoint: 99

  blob_threshold: 0.2
  objectness_threshold: 0.2

  do_validation: False

  checkpoint:
    root: "/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/src/position_maps/logs/"
    path: "lightning_logs/version_"
    version: 424798 # 437363  # 424798

patch_mode:
  use_pretrained:
    enabled: False
    checkpoint:
      root: "/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/src/position_maps/logs/"
      path: "lightning_logs/version_"
      version: 502496 # 492265 # 497829 # 492265 #424798 # 437363  # 424798
      top_k: 1

  patch_size: [256, 256]
  num_epochs: 6000
  batch_size: 2
  mini_batch_size: 2
  num_workers: 0
  pin_memory: True
  drop_last: True

  model: 'DeepLabV3Plus'
  focal_loss_alpha: 0.9
  gaussuan_focal_loss_alpha: 2.0

  subset_indices: [ 0, 85, 32, 5, 125, 200, 220, 240, 1024, 1600, 2600, 4000 ]
  #  subset_indices: [0]

  plot_checkpoint: 99

  patience: 50
  verbose: True
  factor: 0.1
  min_lr: 1e-10




