# @package _global_

device: 'cuda:0'
data_augmentation: 1

# optimizer
# Adam
lr: 5e-3
weight_decay: 0
amsgrad: False

# scheduler
# ReduceLROnPlateau
patience: 5
verbose: True
factor: 0.1
min_lr: 1e-10
# extra
monitor: 'val_loss_epoch'
interval: 'epoch'
frequency: 1

# loaders
batch_size: 4
shuffle: True
num_workers: 0
pin_memory: True
drop_last: False
val_batch_size_factor: 2

# trainer
trainer:
  max_epochs : 400
  gpus : 1
  fast_dev_run: False


# dataset
root: '/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/Datasets/SDD/'
video_class: DEATH_CIRCLE

train:
  num_videos: -1
  video_number_to_use: 2
  multiple_videos: False

val:
  num_videos: -1
  video_number_to_use: 0
  multiple_videos: False

dataset_workers: 8
# keep one of them null at one time
scale_factor: null # 0.25
desired_size: [400, 400]

use_generated_dataset: True

plot_samples: True

# gaussian
sigma: 10

warm_restart:
  enable: True
  custom_load: True
  checkpoint:
    root: "/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/src/position_maps/logs/"
    path: "lightning_logs/version_"
    version: 0




