# @package _global_
# @package _global_

eval:
  test_only_box_crops: True
  device: 'cuda:0'
  num_workers : 12

  data_augmentation: False

  use_resnet: True
  use_pretrained: False
  smaller_resnet: True
  first_in_channel: 3
  first_stride: 2
  first_padding: 1

  batch_size: 3
  shuffle: False
  pin_memory: True

  # dataset
  use_generated_dataset: True

  dataset:
    name: 'stanford'
    num_workers: 12
    video_to_use: 0
    video_class: 'DEATH_CIRCLE'
    num_videos: [3]
    multiple_videos: False
    merge_annotations: False
    root: "/home/rishabh/Thesis/TrajectoryPredictionMastersThesis/Datasets/SDD/"
    # root: "/usr/stud/rajr/storage/user/TrajectoryPredictionMastersThesis/Datasets/SDD/"
    only_long_trajectories: True
    track_length_threshold: 60

    additional_h: 20
    additional_w: 20
#    aspect_ratios: [ 0.75, 0.5 ]
    aspect_ratios: []
#    scales: [ 2.0 ]
    scales: []
    track_length_threshold_for_random_crops: 30
    radius_elimination: 150

  checkpoint:
    path: "lightning_logs/version_"
    version: 10
    object_classifier_version: 8
