# @package _global_
dropout: 0.0
batch_norm: False

# model
unet:
  num_classes: 1
  input_channels: 3
  num_layers: 5
  num_additional_double_conv_layers: 2  # default: 0
  features_start: 64
  bilinear: False

stacked_hourglass:
  num_stacks: 3
  num_classes: 1
  input_channels: 3
  batch_norm: False
  increase: 0
