# @package _global_
dropout: 0.0
batch_norm: False

# model
unet:
  num_classes: 1
  input_channels: 3
  num_layers: 5
  num_additional_double_conv_layers: 1  # default: 0
  features_start: 64
  bilinear: False

stacked_hourglass:
  num_stacks: 3
  num_classes: 1
  input_channels: 3
  batch_norm: False
  increase: 0

trajectory_baseline:
  generator:
    embedding_dim_scalars: 8
    encoder_h_g_scalar: 8
    decoder_h_g_scalar: 16

    pred_len: 12
    noise_scalar: 4
    mlp_vec: 64
    mlp_scalar: 32
    POV: False
    noise_type: "local"
    social_attention: False
    social_dim_scalar: 10
