# @package _global_
dropout: 0.0
batch_norm: False
use_torch_deform_conv: True

# model
unet:
  num_classes: 1
  input_channels: 3
  num_layers: 5
  num_additional_double_conv_layers: 0 # 1 # 0  # default: 0
  features_start: 64
  bilinear: False

# old version
stacked_hourglass:
  num_stacks: 3
  num_classes: 1
  input_channels: 3
  batch_norm: False
  increase: 0

hourglass:
#  downsample_times: 5
  downsample_times: 3
  num_stacks: 2
#  stage_channels: [256, 256, 384, 384, 384, 512]
  stage_channels: [256, 256, 384, 512]
#  stage_blocks: [2, 2, 2, 2, 2, 4]
  stage_blocks: [2, 2, 2, 4]
  feat_channel: 256
  norm_cfg_type: 'BN'
  norm_cfg_requires_grad: True
  pretrained: null
  init_cfg: null

  head:
    num_layers: 2
    bilinear: False
    enable_last_layer_activation: False
    use_conv_deform_conv: True

  last_conv:
    out_channels: 1
    kernel: 3
    stride: 1
    padding: 1

    offset_kernel: 3
    offset_stride: 1
    offset_padding: 1

  upsample_params:
    factor: 2
    mode: bilinear
    align_corners: True
    kernel_bilinear: 1
    kernel: 2
    stride: 2

    offset_kernel: 2
    offset_stride: 2
    offset_padding: 0

  deform:
    groups: 1
    kernel: 3
    padding: 1

  use_deformable_conv: False

trans_unet:
  config: 'R50-ViT-B_16'
  img_size: [256, 256]
  num_classes: 1
  zero_head: False
  vis: False
  use_attn_decoder: True

vit:
  img_size: [256, 256]
  patch_size: 16
  in_channels: 3
  embed_dim: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4
  out_indices: 11
  qkv_bias: True
  qk_scale: null
  drop_rate: 0
  attn_drop_rate: 0
  drop_path_rate: 0
  norm_cfg:
    type: 'LN'
    eps: 1e-6
    requires_grad: True
  act_cfg:
    type: 'GELU'
  norm_eval: False
  final_norm: False
  out_shape: 'NCHW'
  interpolate_mode: 'bicubic'
  with_cls_token: True
  with_cp: False

  seg_head:
    in_channels: 3
    out_channels: 1
    kernel_size: 1
    padding: 0
    stride: 1
    use_bn: True

trajectory_baseline:
  generator:
    embedding_dim_scalars: 8
    encoder_h_g_scalar: 8
    decoder_h_g_scalar: 16

    pred_len: 1
    noise_scalar: 4
    mlp_vec: 64
    mlp_scalar: 32
    POV: False
    noise_type: "local"
    social_attention: False
    social_dim_scalar: 10
